## valid uuid = c63b103c-eab2-47f8-ac50-85a201b00532

### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category 1",
  "description": "Description 1"
}

### List Categories
GET http://localhost:3000/categories

### GET Category
GET http://localhost:3000/categories/c63b103c-eab2-47f8-ac50-85a201b00532