# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0-debian
        env:
          MYSQL_DATABASE: micro_videos
          MYSQL_ROOT_PASSWORD: root
    container: node
    env:
      DB_VENDOR: sqlite
      DB_HOST: ':memory:'
      DB_LOGGING: false
      DB_AUTO_LOAD_MODELS: true

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install
      # - run: npm run build --if-present
      - run: npm test
